name = "wacc"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["wacc"]

[[depends-on]]
aaa = "~0.2.6"

[build-switches]
development.optimization = ["-O0", "-g"]
release.optimization = ["-gnatn2", "-O3", "-march=native"]
